[package]
name = "dlder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = { version = "2.0.1", features = ["windows-console"] }
crossterm = "0.27.0"
winres = "0.1.12"
